### ISSUE TITLE
PayPal Donate

### ISSUE THREAD

**Issue by DoS007** [adelnizamutdinov/TawkTube#23]
Hi there,

this is probably not the right place but I don't know whereelse I can do this:

I really appreciate your work man :). Podcasts are great inspiration resource and to make people able to use youtube (the biggest video plattform with lots of great youtubers) cannels as podcasts, that is insanely great :). So lots of lots of thanks to you :+1:  .

I don't have patreon and don't want to make an account there. Could you please add a paypal donate button on the site? 

Thanks

**Comment by adelnizamutdinov** [comment]
@DoS007 Thanks a bunch for suggestion!
