### ISSUE TITLE
wrong sound for all items in a playlist

### ISSUE THREAD

**Issue by ZoharML** [adelnizamutdinov/TawkTube#24]
I was trying to use this tool to convert this playlist:
https://www.youtube.com/playlist?list=PLx4jClAH_07w9JXxiCweGZz-RHG9BV5eQ

I get the link:
https://limitless-atoll-85321.herokuapp.com/playlist?list=PLx4jClAH_07w9JXxiCweGZz-RHG9BV5eQ

but when I try to use it in MusicBee or Pocket Cast all the tracks have the same strange sound of a old windows PC. all the tracks have the same file size
VLC and winamp cannot play these files.

 
[sound.zip](https://github.com/adelnizamutdinov/TawkTube/files/2246780/sound.zip)

Thanks

Zohar

**Comment by adelnizamutdinov** [comment]
yeah, this is essentially https://github.com/adelnizamutdinov/TawkTube/issues/3

I have a placeholder sound for everything that's copyrighted. YouTube does not serve copyrighted audio, I have to convert these audios myself. But that's a huge project, I don't know when I'll get to it.

**Comment by adelnizamutdinov** [comment]
@ZoharML Basically http://tawktube.com/ is able to serve talk shows and lectures at the moment. Music and other copyrighted stuff is more challenging to serve

**Comment by ZoharML** [comment]
Thanks, 
Hope you will find the time for this.
Zohar

**Comment by adelnizamutdinov** [comment]
fixed in https://github.com/adelnizamutdinov/TawkTube/commit/257bc257bbe503698abc6fba0226dd8f7a0b3168
