### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by meneses-pt** [adelnizamutdinov/TawkTube#28]
There are some "episodes" that I can't download because I get access denied.
Here is one example: http://tawktube.com/audio?v=0DmTzD27_iU
You can check that the id is a valid video.

**Comment by adelnizamutdinov** [comment]
The issue is not there when running locally, so I think google just binds this particular stream to the server's IP.

I think the issue might be solved by implementing proxying for audio streams https://ktor.io/samples/other/reverse-proxy.html
